# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e19234248ce7531490511bc8871d7b410841dc96b75c659369a09b85238c09504a26b8c3ccf1b864afe77b114beb15f50ad50e6fbe51e49e09112aaabdccc548

test:
  secret_key_base: d8447d34671a8021cfc8c21c80350604d4a41f3d49887e0929aecd391cff96fc15b3ec990e26aff554a41152600f84009e440f8d8e208416b237e3c11bc7a2dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
